### ISSUE TITLE
It doesn't replace anything.

### ISSUE THREAD

**Issue by chiqui3d** [fagbokforlaget/strapi-plugin-wysiwyg-toastui#1]
I just installed and it doesn't replace the default editor, is there anything else to do?

**Comment by shardiwal** [comment]
@chiqui3d Make sure you rebuild the project, after installing this package.

**Comment by chiqui3d** [comment]
Ok thanks, I deleted the build folder, and it's already rebuilt and working, do you know how I can put Wysiwyg by default?
