### ISSUE TITLE
Reordering components in dynamic zone does not update editor content

### ISSUE THREAD

**Issue by Lullu08** [fagbokforlaget/strapi-plugin-wysiwyg-toastui#8]
**Hi!**

Thanks for the great plugin! We are very happy using the toastui, especially performance wise it made a big difference in our strapi cms.

However we have one major problem, as we are working with dynamic zones a lot and we are having the same [issue](https://github.com/strapi/strapi/issues/5260) which was fixed on strapis default wysiwyg editor. The [issue](https://github.com/strapi/strapi/issues/5260) already describes the problem pretty well.

For the moment we are not able to translate the implemented solution from that  [issue](https://github.com/strapi/strapi/issues/5260) to our toastui component. Help would be highly appreciated!

One additional note would be that the reordering feature is working!! After saving and reloading the page the elements are where they are supposed to be, however this is not directly visible on the UI as the input values of the editors are not updating initially after reordering. 

**Versions**
Strapi: v3.6.8
Plugin: v0.1.5

Thank you!

**Comment by iapain** [comment]
Hi,

Unfortunately this plugin is not compatible with `>=3.2`. You might either want to downgrade or see this #4

**Comment by Lullu08** [comment]
Oh, I was not aware of that. Thanks for the quick reply. For anyone who is interested, I was able to fix the issue (for now, since it is outdated and should not be done like this anymore), with the patch provided in #4 and some more state handling that checks if change of value occurred through typing or something else (like reordering).
